version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    env_file:
      - ./db/db.env

  web:
    build: ./Uwrite
    command: gunicorn Uwrite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./Uwrite/static:/app/static
      - ./Uwrite/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./Uwrite/.env

volumes:
  postgres_data:
  static_volume:
  media_volume: