# Generated by Django 5.0.6 on 2024-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_file_alter_product_author'),
        ('users', '0002_alter_profile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(default=None, to='myapp.product'),
        ),
    ]
