# Generated by Django 5.0.6 on 2024-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tasks_product_tasks'),
        ('users', '0003_profile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complite_tasks',
            field=models.ManyToManyField(default=None, to='myapp.tasks'),
        ),
    ]
