# Generated by Django 5.0.6 on 2024-06-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_complite_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='complite_tasks',
            new_name='complited_tasks',
        ),
    ]
