# Generated by Django 5.0.6 on 2024-06-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_complite_tasks_profile_complited_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='complited_tasks',
            new_name='completed_tasks',
        ),
    ]
